### ISSUE TITLE
GeoDistributedSampler

### ISSUE THREAD

**Issue by FreqBayes** [Tsinghua-MARS-Lab/neural_map_prior#8]
Hi @abbyxxn, deeply appreciate for your great work! I was trying to finetune nmp after trained bevformer_30m_60m for 24 epochs on 8*3090 with the same requirements but got:

> 2023-08-12 08:36:16,655 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> * 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> * 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> * 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> * 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> * 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> * 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> * 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> epoch: 0 self.train_epoch_point: -2
>   0%|                                                                                                                                                                | 0/11 [00:00<?, ?it/s]epoch: 0 self.train_epoch_point: -2
>   9%|█████████████▊                                                                                                                                          | 1/11 [00:02<00:24,  2.48s/it]epoch: 0 self.train_epoch_point: -2
>   0%|                                                                                                                                                                 | 0/8 [00:00<?, ?it/s]epoch: 0 self.train_epoch_point: -2
>  18%|███████████████████████████▋                                                                                                                            | 2/11 [00:04<00:20,  2.32s/it]epoch: 0 self.train_epoch_point: -2
>   0%|                                                                                                                                                                 | 0/6 [00:00<?, ?it/s]GeoDistributedSamplerGeoDistributedSamplerGeoDistributedSampler  shuffle shuffle shuffle
> epoch: 0 self.train_epoch_point: -2
>   0%|                                                                                                                                                                 | 0/3 [00:00<?, ?it/s]epoch: 0 self.train_epoch_point: -2
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:02<00:00, 20.90s/it]
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:05<00:00, 21.78s/it]
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:07<00:00,  8.48s/it]
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:06<00:00, 16.71s/it]
>  18%|██████████████████████████▊                                                                                                                             | 3/17 [01:26<07:36, 32.60s/it]gpu_id: 2 count: tensor(0.) gpu_city_list ['boston-seaport_map_3_1', 'boston-seaport_map_1_1', 'boston-seaport_map_0_2']
> create empty map for: map_slice_float_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'float32', 'embed_dims': 256, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 97.24it/s]
>  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 5/6 [01:22<00:16, 16.09s/it]gpu_id: 2 count: tensor(0) gpu_city_list ['boston-seaport_map_3_1', 'boston-seaport_map_1_1', 'boston-seaport_map_0_2']
> create empty map for: map_slice_int_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'int16', 'embed_dims': 1, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [01:22<00:00, 13.82s/it]
>  24%|███████████████████████████████████▊                                                                                                                    | 4/17 [01:28<04:26, 20.53s/it]gpu_id: 5 count: tensor(0.) gpu_city_list ['singapore-onenorth_map_0_1', 'singapore-onenorth_map_2_3', 'singapore-onenorth_map_2_2', 'singapore-onenorth_map_1_1', 'singapore-onenorth_map_1_3', 'singapore-onenorth_map_0_2', 'singapore-onenorth_map_3_1', 'singapore-onenorth_map_3_0']
> create empty map for: map_slice_float_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'float32', 'embed_dims': 256, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 638.75it/s]
> gpu_id: 5 count: tensor(0) gpu_city_list ['singapore-onenorth_map_0_1', 'singapore-onenorth_map_2_3', 'singapore-onenorth_map_2_2', 'singapore-onenorth_map_1_1', 'singapore-onenorth_map_1_3', 'singapore-onenorth_map_0_2', 'singapore-onenorth_map_3_1', 'singapore-onenorth_map_3_0']
> create empty map for: map_slice_int_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'int16', 'embed_dims': 1, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
>  29%|████████████████████████████████████████████▋                                                                                                           | 5/17 [01:30<02:45, 13.77s/it]ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 6 (pid: 3624545) of binary: /opt/conda/bin/python
> ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
> INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group

then torch tried to restart the Worker group and stuck. It looks like something went wrong with GeoDistributedSampler that does not reading files properly in my case. I tried to change if shuffle condition in mmdet_dataloader.py and some other configs but with no luck. My pickled ann_files are generated from data_sampler.py and nusc_city_infos.py, the root directories had been replace in lane_render.py. 

I was wondering is there something missing or I loaded the data in a wrong way? Btw, I also trained the baseline of 24 epochs of _city_split but "CUDA out of memory" while starting to finetune it. Appreciate for your help in advance.

**Comment by abbyxxn** [comment]
Thanks for your interest! Perhaps it is just out of memory. You can try freezing the backbone and FPN.

**Comment by FreqBayes** [comment]
> Thanks for your interest! Perhaps it is just out of memory. You can try freezing the backbone and FPN.

Thank you for the reply! I checked the GPU while training by nvidia-smi, it only takes a little more than 13G to run fine tuning but the Worker group kept failing to launch. Though city_split can be tuned after backbone and neck been frozen, then encountered the same problem at the beginning of epoch 2 or during epoch 3. 

Wondering if it normal for the situations like(bar ended early):
 18%|██████████████████████████▊ | 3/17 [01:26<07:36, 32.60s/it]gpu_id: 2 count: tensor(0.) gpu_city_list ['boston-seaport_map_3_1', 'boston-seaport_map_1_1', 'boston-seaport_map_0_2'] while resetting the map?

**Comment by FreqBayes** [comment]
> Thanks for your interest! Perhaps it is just out of memory. You can try freezing the backbone and FPN.

Thank you for the reply! I checked the RAM usage while fine tuning with 8 GPUs where it exceeded the maximum. Had to limit the frozen_stage and batch_size and now it works.

**Comment by CBQ-1223** [comment]
我看您的做法是第二阶段;训练时去冻结backbone和neck层,请问您具体是怎么冻结的呢,cfg里面我看是没有冻结的

**Comment by FreqBayes** [comment]
> 我看您的做法是第二阶段;训练时去冻结backbone和neck层,请问您具体是怎么冻结的呢,cfg里面我看是没有冻结的

ResNet 可以用自带的 frozen_stages=4，FPN的话需要optimizer里面加上类似paramwise_cfg=dict(custom_keys={'FPN': dict(lr_mult=0.0, decay_mult=0.0)}) 这样的选项让weights不更新，时间久远已经记不清了

**Comment by CBQ-1223** [comment]
好嘞明白啦，谢谢大佬



发自我的iPhone


------------------ Original ------------------
From: FreqBayes ***@***.***&gt;
Date: Tue,Feb 25,2025 9:34 AM
To: Tsinghua-MARS-Lab/neural_map_prior ***@***.***&gt;
Cc: Baoquan Chen ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Tsinghua-MARS-Lab/neural_map_prior] GeoDistributedSampler (Issue#8)



    
我看您的做法是第二阶段;训练时去冻结backbone和neck层,请问您具体是怎么冻结的呢,cfg里面我看是没有冻结的
  
ResNet 可以用自带的 frozen_stages=4，FPN的话需要optimizer里面加上类似paramwise_cfg=dict(custom_keys={'FPN': dict(lr_mult=0.0, decay_mult=0.0)}) 这样的选项让weights不更新，时间久远已经记不清了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  FreqBayes left a comment (Tsinghua-MARS-Lab/neural_map_prior#8)
  
我看您的做法是第二阶段;训练时去冻结backbone和neck层,请问您具体是怎么冻结的呢,cfg里面我看是没有冻结的
  
ResNet 可以用自带的 frozen_stages=4，FPN的话需要optimizer里面加上类似paramwise_cfg=dict(custom_keys={'FPN': dict(lr_mult=0.0, decay_mult=0.0)}) 这样的选项让weights不更新，时间久远已经记不清了
